### ISSUE TITLE
socket hang up errors

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#1]
jsreportonline quite often response "socket hang up errors". This means mostly that the container was killed by OS cgroup because of the memory limit. I verify this by calling the `dmesg -T` on the machine host which gives me exact information when the OS killed the process.

It is common case that a user overloads the container, but the message "socket hang up" is not informative at all. We are not able to provide exact information why the phantomjs or node process in the container was killed, so I tried to at least give hint to users by these lines
https://github.com/jsreportonline/main/blob/master/lib/phantom.js#L51
Unfortunately it doesn't seem to be working in production, there are only "socket hang up" errors in the logs.

@bjrmatos 
Please try to find out why it is not working, also let me know if you know about better way how to deal with this.

**Comment by bjrmatos** [comment]
the reason for why it was not working is because we were trying to look for the hang up error in the wrong place, the hang out error is present in the error param of the request callback `(error, httpResponse) => {}` or in the .catch handler of the promise when `request` is promisified 😃

**Comment by bjrmatos** [comment]
i've also added a check for `err.code === 'ECONNRESET'` since this is the node js error code thrown when a connection is abruptly closed

**Comment by pofider** [comment]
Ok. Thanks.
