### ISSUE TITLE
async reports fail in jo

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#10]
Request

```js
{
"template": {
"engine": "handlebars",
"recipe": "phantom-pdf",
"content":"html template here"
 },
"data":{},
"options": { 
  "reports": {  
    "async": true
  }
}
}
```

Error
`
Async reports extension render failed TypeError: Cannot read property 'name' of undefined at addTenant (/usr/src/app/lib/init.js:106:32) at Function.col.beforeFindListeners.add (/usr/src/app/lib/init.js:113:63) at /usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/lib/listenerCollection.js:172:41 at /usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/lib/listenerCollection.js:151:24 at _fulfilled (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:794:54) at self.promiseDispatch.done (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:823:30) at Promise.promise.promiseDispatch (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:756:13) at /usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:516:49 at flush (/usr/src/app/node_modules/jsreport-mongodb-store/node_modules/listener-collection/node_modules/q/q.js:110:17) at _combinedTickCallback (internal/process/next_tick.js:73:7) at process._tickDomainCallback (internal/process/next_tick.js:128:9)
`

**Comment by bjrmatos** [comment]
i can confirm that async reports are working in jo v2, so this will be fixed when landing the new version to production

**Comment by pofider** [comment]
Yes working now.
