### ISSUE TITLE
wkhtmltopdf debug logs

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#2]
Template like this should return the 'hello' message in debug logs in wkhtmltopdf recipe.
```html
<script>
    console.log('hello')
</script>
```

This was implemented recently in `jsreport-wkhtmltopdf@1.2` I guess. We should propagate this change also the the jsreportonline

**Comment by bjrmatos** [comment]
for some reason the logs from `console.log` in template are not present in the stdout content of `wkhtmltopdf` when running inside the docker containers. i can confirm that the log is present when running in OSX (and i guess that in windows too) but when running in docker (or maybe linux in general) `wkhtmltopdf` doesn't include the logs from `console` in stdout.
