### ISSUE TITLE
Logs cut from the startuppage

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#39]
There are missing entries in the jsreportonline output logs on the startup page

![image](https://user-images.githubusercontent.com/2041960/68544650-b21e6b00-03c5-11ea-8433-344e8303d37f.png)

There are some tweaks to avoid duplicating entries in the loggly, however, this is missing in the studio.

**Comment by bjrmatos** [comment]
this was solved in new version of jsreport, just updating the deps and this is no longer an issue
