### ISSUE TITLE
Installation of custom modules

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#48]
Just an idea for future evaluation...

How about we let customers install custom npm modules:
```
const jsreport  = require('jsreport-proxy')

async function beforeRender(req, res) {
  const axios = jsreport.npm.require('axios@1.5.2')
  await axios.get(....)
}
```

Technically the proxy `jsreport.npm.require` would install the package to the linked tmpfs.
This would run only once. So until the container is restarted this would be there in memory and very quickly accessible.

Not sure how this would fit into helpers though.

**Comment by pofider** [comment]
@bjrmatos How do you feel about this?

**Comment by bjrmatos** [comment]
hmmm i think i like the idea, and technically since the sandbox is a secure env then we should be fine also

**Comment by pofider** [comment]
This was already implemented as part of jsreport.
