### ISSUE TITLE
winston logs too many report.log files to the app root

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#56]

**Comment by bjrmatos** [comment]
I believe there are two options here:

- use the [maxFiles option](https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport) of file built in transport, though during my testing on my computer the max files option is not really limiting the max files created, but instead it has some weird logic that gets confused with the counter added to the log file
- use [winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file) which maxSize option seems to work as expected according to my tests

i guess we use the winston-daily-rotate-file unless you have some comments about it.
