### ISSUE TITLE
"Protocol error (Page.printToPDF): Printing failed" with specific report requests

### ISSUE THREAD

**Issue by Ackhuman** [jsreportonline/main#58]
We are using JsReport Online to render cross-tab reports on survey data we collect. They have been working fine, but recently we have been getting errors when we try to render the report for questions that have 8 or more choices. The exact same report and data will work if we combine columns to 7 or fewer. However, this same issue does not appear using a local instance, even with the same server version as JsReport Online. That leads me to believe there is something specific in the server configuration that results in this error. I'm not sure what configuration is used on Online, so I haven't been able to reproduce using a local server.

The remote error call stack is as follows:

`{"message":"Protocol error (Page.printToPDF): Printing failed","stack":"ProtocolError: Protocol error (Page.printToPDF): Printing failed
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:286:24
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:282:16)
    at Page.createPDFStream (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1963:85)
    at Page.pdf (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1993:37)
    at /app/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:382:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:423:22"}`

I tried and failed to create a minimal repro input, so I have pulled working and non-working versions of the actual report inputs and put them in [this OneDrive folder](https://1drv.ms/u/s!ArXkphglS0fChnu5cuFAGrwOljUN?e=FyWTwR).

**Comment by Ackhuman** [comment]
Did anything change in the JsReport Online configuration since this ticket was opened?

**Comment by pofider** [comment]
Ups, I didn't notice this ticket.

There was no change regarding chrome version. 
Today we doubled the swap memory available for the user's container.

I will check your onedrive data and come back.

**Comment by Ackhuman** [comment]
I ask because the report we were having trouble with before is now working, despite the version being the same. Since the same JsReport version worked locally I've been assuming the issue is configuration. Maybe the improved hardware fixed the issue. I will close this since it's working.

**Comment by pofider** [comment]
I've tested your data with original and increased memory and I confirm this change helps to successfully finish the report rendering.

**Comment by Ackhuman** [comment]
Thanks for verifying that, Jan.
